window.env = {
  "USER": "kferreira",
  "npm_config_user_agent": "npm/10.8.3 node/v18.20.2 linux x64 workspaces/false",
  "npm_node_execpath": "/home/kferreira/.nvm/versions/node/v18.20.2/bin/node",
  "SHLVL": "1",
  "BROWSER": "explorer.exe",
  "npm_config_noproxy": "",
  "HOME": "/home/kferreira",
  "OLDPWD": "/mnt/c/Users/kyanf/OneDrive/Documents/Coursework/Capstone Project/AccountOpeningFileUpload/capstone_project",
  "NVM_BIN": "/home/kferreira/.nvm/versions/node/v18.20.2/bin",
  "npm_package_json": "/mnt/c/Users/kyanf/OneDrive/Documents/Coursework/Capstone Project/AccountOpeningFileUpload/capstone_project/package.json",
  "NVM_INC": "/home/kferreira/.nvm/versions/node/v18.20.2/include/node",
  "HOMEBREW_PREFIX": "/home/linuxbrew/.linuxbrew",
  "npm_config_userconfig": "/home/kferreira/.npmrc",
  "npm_config_local_prefix": "/mnt/c/Users/kyanf/OneDrive/Documents/Coursework/Capstone Project/AccountOpeningFileUpload/capstone_project",
  "DBUS_SESSION_BUS_ADDRESS": "unix:path=/run/user/1000/bus",
  "WSL_DISTRO_NAME": "Ubuntu",
  "COLOR": "1",
  "NVM_DIR": "/home/kferreira/.nvm",
  "WAYLAND_DISPLAY": "wayland-0",
  "INFOPATH": "/home/linuxbrew/.linuxbrew/share/info:",
  "LOGNAME": "kferreira",
  "PULSE_SERVER": "unix:/mnt/wslg/PulseServer",
  "WSL_INTEROP": "/run/WSL/74476_interop",
  "NAME": "DESKTOP-FS8P5F7",
  "_": "/home/kferreira/.nvm/versions/node/v18.20.2/bin/npm",
  "npm_config_prefix": "/home/kferreira/.nvm/versions/node/v18.20.2",
  "npm_config_npm_version": "10.8.3",
  "TERM": "xterm-256color",
  "npm_config_cache": "/home/kferreira/.npm",
  "npm_config_node_gyp": "/home/kferreira/.nvm/versions/node/v18.20.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js",
  "PATH": "/mnt/c/Users/kyanf/OneDrive/Documents/Coursework/Capstone Project/AccountOpeningFileUpload/capstone_project/node_modules/.bin:/mnt/c/Users/kyanf/OneDrive/Documents/Coursework/Capstone Project/AccountOpeningFileUpload/node_modules/.bin:/mnt/c/Users/kyanf/OneDrive/Documents/Coursework/Capstone Project/node_modules/.bin:/mnt/c/Users/kyanf/OneDrive/Documents/Coursework/node_modules/.bin:/mnt/c/Users/kyanf/OneDrive/Documents/node_modules/.bin:/mnt/c/Users/kyanf/OneDrive/node_modules/.bin:/mnt/c/Users/kyanf/node_modules/.bin:/mnt/c/Users/node_modules/.bin:/mnt/c/node_modules/.bin:/mnt/node_modules/.bin:/node_modules/.bin:/home/kferreira/.nvm/versions/node/v18.20.2/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/node-gyp-bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/kferreira/.nvm/versions/node:/home/kferreira/.nvm/versions/node/v18.20.2/bin:/home/kferreira/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Program Files/Common Files/Oracle/Java/javapath:/mnt/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/dotnet/:/mnt/c/Users/kyanf/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/kyanf/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Program Files/sfdx/bin:/mnt/c/Users/kyanf/OneDrive/Documents/Salesforce Coding/sfdx/bin",
  "HOMEBREW_CELLAR": "/home/linuxbrew/.linuxbrew/Cellar",
  "NODE": "/home/kferreira/.nvm/versions/node/v18.20.2/bin/node",
  "npm_package_name": "capstone_project",
  "XDG_RUNTIME_DIR": "/run/user/1000/",
  "DISPLAY": ":0",
  "LANG": "C.UTF-8",
  "npm_lifecycle_script": "react-dotenv && vite",
  "SHELL": "/bin/zsh",
  "npm_package_version": "0.0.0",
  "npm_lifecycle_event": "dev",
  "npm_config_globalconfig": "/home/kferreira/.nvm/versions/node/v18.20.2/etc/npmrc",
  "npm_config_init_module": "/home/kferreira/.npm-init.js",
  "PWD": "/mnt/c/Users/kyanf/OneDrive/Documents/Coursework/Capstone Project/AccountOpeningFileUpload/capstone_project",
  "npm_execpath": "/home/kferreira/.nvm/versions/node/v18.20.2/lib/node_modules/npm/bin/npm-cli.js",
  "NVM_CD_FLAGS": "-q",
  "npm_config_global_prefix": "/home/kferreira/.nvm/versions/node/v18.20.2",
  "HOMEBREW_REPOSITORY": "/home/linuxbrew/.linuxbrew/Homebrew",
  "npm_command": "run-script",
  "HOSTTYPE": "x86_64",
  "WSL2_GUI_APPS_ENABLED": "1",
  "MANPATH": "/home/linuxbrew/.linuxbrew/share/man::",
  "WSLENV": "",
  "EDITOR": "code -w",
  "INIT_CWD": "/mnt/c/Users/kyanf/OneDrive/Documents/Coursework/Capstone Project/AccountOpeningFileUpload/capstone_project",
  "VITE_APP_CLIENT_ID": "3MVG9XgkMlifdwVCsrdJm8wmHR6azcmfdYD3OmA8hfQQH.ShXd.jADs38DqmkHSwWIXijIqUWvExmdsDogzxH",
  "VITE_APP_CLIENT_SECRET": "5DBBB8BCB1FB653E509AE280632526ED0947F74EC9509CD2C88D5793B3F61159",
  "VITE_SALESFORCE_USERNAME": "api_only@sandbox.com",
  "VITE_SALESFORCE_PASSWORD": "Test123*!&*&",
  "VITE_SALESFORCE_SECURITY_TOKEN": "tec6dPkIM3XrMrX70DxbGieFn",
  "VITE_SALESFORCE_LOGIN_URL": "https://interaudibank-dev-ed.develop.my.salesforce.com",
  "VITE_SALESFORCE_INSTANCE_URL": "https://interaudibank-dev-ed.develop.my.salesforce.com"
};